executableModuleName=webfx-demo-fx2048-application-teavm-js
executableModuleVersion=0.1.0-SNAPSHOT
applicationModuleName=webfx-demo-fx2048-application
pwa=false
mavenBuildTimestamp=${maven.build.timestamp}
environment=${webfx.meta.environment}